### ISSUE TITLE
Bug in  FILE CRAWLER

### ISSUE THREAD

**Issue by longfeili5170** [Novartis/cellxgene-gateway#40] opened 2021-02-02 07:33 UTC
Hi !
This tool is very useful, but I encountered some problems in the process of using it.
I have Mouse.h5ad in the file, but I can't open it.
The error is as follows：
<img width="940" alt="屏幕快照 2021-02-02 下午3 32 35" src="https://user-images.githubusercontent.com/68364890/106566891-e999aa00-656b-11eb-867e-1a46bf23cbbe.png">

**Comment by alokito** [comment] 2021-04-03 11:34
Hello and thanks for reporting this issue. Unfortunately, I have been unable to reproduce it. The error is coming from the underlying cellxgene program, are you able to view this dataset directly with cellxgene? If you look at the logs of cellxgene-gateway, it will print out the launch command that was used to launch cellxgene. It may be that you need to use a newer version of cellxgene, or there was some issue in the pipeline that produced the Mouse.h5ad file.

**Comment by alokito** [comment] 2021-11-14 22:36
closing because I cannot reproduce.

**Closed by alokito** 2021-11-14 22:36 UTC
Labels: reprex needed
